version: '3.8'

services:
  backend:
    image: python:3.11
    volumes:
      - ./src/backend:/app
    working_dir: /app
    command: python app.py
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/mydatabase

  frontend:
    image: python:3.11
    volumes:
      - ./src/frontend:/app
    working_dir: /app
    command: streamlit run app.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./src/database/db-data:/var/lib/postgresql/data

volumes:
  db-data:
