version: '3.8'

services:
  backend:
    volumes:
      - ./backend:/app
    working_dir: /app
    command: python backend/app.py
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/mydatabase
    depends_on:
      - db

  frontend:
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: streamlit run frontend/app.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    depends_on:
      - backend

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./src/database/db-data:/var/lib/postgresql/data

volumes:
  db-data:
