version: '3.8'

services:
  backend:
    # volumes:
    #   - ./backend:/app
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /app/snekdash_backend
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+psycopg2://user:password@db:5432/mydatabase
      - GITHUB_API_TOKEN=${GITHUB_API_TOKEN}
      - GITHUB_CLASSIC_API_TOKEN=${GITHUB_CLASSIC_API_TOKEN}
    depends_on:
      - db

  frontend:
    # volumes:
    #   - ./frontend:/app
    build:
      context: ./frontend
      dockerfile: Dockerfile
    working_dir: /app
    command: streamlit run snekdash_frontend/app.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    depends_on:
      - backend

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./database/db-data:/var/lib/postgresql/data

volumes:
  db-data:
